=== lizzyl/bootstrap-test/json-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "head": {
      "description": "head part",
      "type": "object",
      "properties": {
        "meta": {
          "description": "meta info in head",
          "type": "object",
          "properties": {
            "keywords": {
              "type": "string"
            },
            "description": {
              "type": "string"
            },
            "author": {
              "type": "string"
            }
          }
        },
        "title": {
          "type": "string"
        },
        "favicon": {
          "type": "string"
        }
      },
      "required": ["title"]
    },
    "header": {
      "type": "object",
      "properties": {
        "logo": {
          "type": "object",
          "properties": {
            "url": {
              "type": "string"
            },
            "src": {
              "type": "string"
            }
          },
          "required": ["url", "src"]
        },
        "nav": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "url": {
                "type": "string"
              }
            },
            "required": ["name", "url"]
          }
        },
        "account": {
          "type": "object",
          "properties": {
            "signup": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "url": {
                  "type": "string"
                }
              }
            },
            "signin": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "url": {
                  "type": "string"
                }
              }
            },
            "logout": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "url": {
                  "type": "string"
                }
              }
            }
          }
        }
      },
      "required": ["logo", "nav"]
    },
    "footer": {
      "type": "object",
      "properties": {
        "copyright": {
          "type": "string"
        },
        "address": {
          "type": "string"
        },
        "icpLicense": {
          "type": "string"
        }
      },
      "required": ["copyright", "address"]
    },
    "content": {
      "type": "object",
      "properties": {
        "carousel": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "object",
            "properties": {
              "src": {
                "type": "string"
              },
              "url": {
                "type": "string"
              },
              "title": {
                "type": "string"
              },
              "alt": {
                "type": "string"
              }
            },
            "required": ["src"]
          }
        },
        "bannerUrl": {
          "type": "string"
        },
        "main": {
          "type": "object"
        }
      },
      "required": ["main"]
    }
  },
  "required": ["head", "header", "footer", "content"]
}

=== lizzyl/bootstrap-test/data/dispute.json
{
  "head": {
    "meta": {
      "keywords": "霍尔果斯炫动网络官网",
      "description": "霍尔果斯炫动网络官网",
      "author": "your-name@hoolai.com"
    },
    "title": "官网首页"
  },
  "header": {
    "logo": {
      "src": "http://cdn.hoolaiimg.com/group1/M00/00/2B/CgIJKlg-iz2ARC8SAAAjKGI-JWw474.png",
      "url": "./"
    },
    "nav": [{
      "name": "首页",
      "url": "./index.html"
    }, {
      "name": "关于我们",
      "url": "./about.html"
    }, {
      "name": "家长监护工程",
      "url": "./custody.html"
    }, {
      "name": "在线交易",
      "url": "./pay.html"
    }, {
      "name": "服务协议",
      "url": "./server.html"
    }, {
      "name": "隐私协议",
      "url": "./privacy.html"
    }, {
      "name": "纠纷处理",
      "url": "./dispute.html"
    }],
    "account": {
      "signup": {
        "name": "注册",
        "url": "./signup.html"
      },
      "signin": {
        "name": "登陆",
        "url": "./signin.html"
      },
      "logout": {
        "name": "注销",
        "url": "./logout.html"
      }
    }
  },
  "footer": {
    "copyright": "霍尔果斯炫动网络科技有限公司",
    "address": "新疆伊犁州霍尔果斯市北京路以西、珠海路以南合作中心配套区查验业务楼8楼8-13-85号"
  },
  "content": {
    "carousel": [{
      "src": "http://cdn.hoolaiimg.com/group1/M00/00/29/CgIJKlfogeWAbJZmAALTKsqjajs799.jpg?v=0.0.1"
    }, {
      "src": "http://cdn.hoolaiimg.com/group1/M00/00/28/PBzLUVc6fvSAeUi8AAMYBqU2do0253.jpg?v=0.0.1"
    }],
    "main": {
      "dispute": {
        "title": "纠纷处理",
        "description": [],
        "content": [{
          "title": "一、【协议的范围】",
          "description": [{
            "content": "1.1本协议是您与互爱之间关于用户使用互爱相关服务所订立的协议。“互爱”是指互爱互动（北京）科技有限公司及其相关服务可能存在的运营关联单位。“用户”是指使用互爱相关服务的使用人，在本协议中更多地称为“您”。"
          }, {
            "content": "1.2本协议项下的服务是指互爱向用户提供的包括但不限于即时通讯、网络媒体、互联网增值、互动娱乐、电子商务和广告等产品及服务（以下简称“本服务”）。"
          }]
        }, {
          "title": "二、【帐号与密码安全】",
          "description": [{
            "content": "2.1您在使用互爱的服务时可能需要注册一个帐号。关于您使用帐号的具体规则，请遵守单独协议。"
          }, {
            "content": "2.2互爱特别提醒您应妥善保管您的帐号和密码。当您使用完毕后，应安全退出。因您保管不善可能导致遭受盗号或密码失窃，责任由您自行承担。"
          }]
        }]
      }
    }
  }
}

=== lizzyl/bootstrap-test/data/home.json
{
  "head": {
    "meta": {
      "keywords": "霍尔果斯炫动网络官网",
      "description": "霍尔果斯炫动网络官网",
      "author": "your-name@hoolai.com"
    },
    "title": "官网首页"
  },
  "header": {
    "logo": {
      "src": "http://cdn.hoolaiimg.com/group1/M00/00/2B/CgIJKlg-iz2ARC8SAAAjKGI-JWw474.png",
      "url": "./"
    },
    "nav": [{
      "name": "首页",
      "url": "./index.html"
    }, {
      "name": "关于我们",
      "url": "./about.html"
    }, {
      "name": "家长监护工程",
      "url": "./custody.html"
    }, {
      "name": "在线交易",
      "url": "./pay.html"
    }, {
      "name": "服务协议",
      "url": "./server.html"
    }, {
      "name": "隐私协议",
      "url": "./privacy.html"
    }, {
      "name": "纠纷处理",
      "url": "./dispute.html"
    }],
    "account": {
      "signup": {
        "name": "注册",
        "url": "./signup.html"
      },
      "signin": {
        "name": "登陆",
        "url": "./signin.html"
      },
      "logout": {
        "name": "注销",
        "url": "./logout.html"
      }
    }
  },
  "footer": {
    "copyright": "霍尔果斯炫动网络科技有限公司",
    "address": "新疆伊犁州霍尔果斯市北京路以西、珠海路以南合作中心配套区查验业务楼8楼8-13-85号"
  },
  "content": {
    "bannerUrl": "http://www.hoolai.com/assets/images/about_hoolai.jpg",
    "carousel": [{
      "src": "http://cdn.hoolaiimg.com/group1/M00/00/29/CgIJKlfogeWAbJZmAALTKsqjajs799.jpg?v=0.0.1"
    }, {
      "src": "http://cdn.hoolaiimg.com/group1/M00/00/28/PBzLUVc6fvSAeUi8AAMYBqU2do0253.jpg?v=0.0.1"
    }],
    "main": {
      "productList": [{
        "id": "1",
        "title": "探墓风云",
        "description": "《探墓风云》是大型3DMMO地宫探险国战手游。游戏邀请“中国悬疑大师”蔡骏代言，共同构建宏大的地宫世界！玩家将从三国曹操墓开始，以探墓者的身份深入地宫古墓，展开一段惊心动魄悬念迭生的探险之旅。探墓摸金、地宫探险、寻龙转生、捉妖养宠、挑战粽子、天梯赛PK、征战万国……多样玩法打造一个令人震撼的悬疑世界。",
        "imgUrl": "http://cdn.hoolaiimg.com/group1/M00/00/29/CgIJKlfogqeAMvtaAABLX6afjJw295.jpg",
        "pageUrl": "http://tmfy.hulai.com/",
        "downloadUrl": "http://www.hoolai.com/h5/22",
        "logoUrl": "http://cdn.hoolaiimg.com/group1/M00/00/2A/CgIJK1fogxOAI-KSAAAgQHSqpQg810.jpg"
      }, {
        "id": "2",
        "title": "焚天之怒【手游】",
        "description": "独特的世界观，丰富有趣的玩法，强大的交互体验。由同名玄幻人气小说改编，小说作者亲自担任首席架构师的首款小说定制手游《焚天之怒》，带你领略真实的修仙世界，一怒红颜，焚神灭天，一同见证天帝重生！",
        "imgUrl": "http://cdn.hoolaiimg.com/group1/M00/00/28/PBzLUVc6jXGASQAKAAFsCi6ve7M610.jpg?v=0.0.1",
        "pageUrl": "http://ft.hoolaigames.com/",
        "downloadUrl": "http://www.hoolai.com/h5/17",
        "logoUrl": "http://cdn.hoolaiimg.com/group1/M00/00/28/PBzLUlc6hR2ADmFxAAAhlU5i7go379.jpg?v=0.0.1"
      }]
    }
  }
}

=== lizzyl/bootstrap-test/data/about.json
{
  "head": {
    "meta": {
      "keywords": "霍尔果斯炫动网络官网",
      "description": "霍尔果斯炫动网络官网",
      "author": "your-name@hoolai.com"
    },
    "title": "关于公司"
  },
  "header": {
    "logo": {
      "src": "http://cdn.hoolaiimg.com/group1/M00/00/2B/CgIJKlg-iz2ARC8SAAAjKGI-JWw474.png",
      "url": "/"
    },
    "nav": [{
      "name": "首页",
      "url": "./index.html"
    }, {
      "name": "关于我们",
      "url": "./about.html"
    }, {
      "name": "家长监护工程",
      "url": "./custody.html"
    }, {
      "name": "在线交易",
      "url": "./pay.html"
    }, {
      "name": "服务协议",
      "url": "./server.html"
    }, {
      "name": "隐私协议",
      "url": "./privacy.html"
    }, {
      "name": "纠纷处理",
      "url": "./dispute.html"
    }],
    "account": {
      "signup": {
        "name": "注册",
        "url": "/signup.html"
      },
      "signin": {
        "name": "登陆",
        "url": "/signin.html"
      },
      "logout": {
        "name": "注销",
        "url": "/logout.html"
      }
    }
  },
  "footer": {
    "copyright": "霍尔果斯炫动网络科技有限公司",
    "address": "新疆伊犁州霍尔果斯市北京路以西、珠海路以南合作中心配套区查验业务楼8楼8-13-85号"
  },
  "content": {
    "carousel": [],
    "bannerUrl": "http://www.hoolai.com/assets/images/about_hoolai.jpg",
    "main": {
      "aboutUs": {
        "companyInfo": {
          "title": "公司简介",
          "description": [{
            "content": "霍尔果斯炫动网络科技有限公司是一家网络游戏研发、运营公司，于2016年成立。公司以专业一流的研发能力和对玩家负责的态度，用心制作着每一款游戏，也体验着游戏带来的快乐与幸福。公司管理层具有丰富的管理和运营经验。公司成立至今，先后研发并运营大型多人在线游戏，主要包括：《焚天之怒》、《探墓风云》等，这些产品取得了骄人业绩的同时，也受到业界及玩家的极大好评。公司提供丰厚的薪酬和最完善的福利制度，提倡打破层级部门的学习氛围，建立开放、平等、务实的企业文化，全力帮助每一个不甘平庸的员工，实现自己的职业理想。渴望所有热爱游戏，坚持理想的年轻人，加入我们，一起用最澎湃的热情，最自由的创造，最执着的勤奋，打造出更多受欢迎的优质游戏作品。"
          }, {
            "content": "公司地址：新疆伊犁州霍尔果斯市北京路以西、珠海路以南合作中心配套区查验业务楼8楼8-13-85号"
          }]
        },
        "companyCulture": {}
      }
    }
  }
}

=== lizzyl/bootstrap-test/data/custody.json
{
  "head": {
    "meta": {
      "keywords": "霍尔果斯炫动网络官网",
      "description": "霍尔果斯炫动网络官网",
      "author": "your-name@hoolai.com"
    },
    "title": "官网首页"
  },
  "header": {
    "logo": {
      "src": "http://cdn.hoolaiimg.com/group1/M00/00/2B/CgIJKlg-iz2ARC8SAAAjKGI-JWw474.png",
      "url": "./"
    },
    "nav": [{
      "name": "首页",
      "url": "./index.html"
    }, {
      "name": "关于我们",
      "url": "./about.html"
    }, {
      "name": "家长监护工程",
      "url": "./custody.html"
    }, {
      "name": "在线交易",
      "url": "./pay.html"
    }, {
      "name": "服务协议",
      "url": "./server.html"
    }, {
      "name": "隐私协议",
      "url": "./privacy.html"
    }, {
      "name": "纠纷处理",
      "url": "./dispute.html"
    }],
    "account": {
      "signup": {
        "name": "注册",
        "url": "./signup.html"
      },
      "signin": {
        "name": "登陆",
        "url": "./signin.html"
      },
      "logout": {
        "name": "注销",
        "url": "./logout.html"
      }
    }
  },
  "footer": {
    "copyright": "霍尔果斯炫动网络科技有限公司",
    "address": "新疆伊犁州霍尔果斯市北京路以西、珠海路以南合作中心配套区查验业务楼8楼8-13-85号"
  },
  "content": {
    "main": {
      "custody": {
        "title": "家长监护工程",
        "description": [],
        "content": [{
          "title": "网络游戏未成年人家长监护工程系统说明",
          "description": [{
            "content": "“网络游戏未成年人家长监护工程”是一项由六家网络游戏企业共同发起并参与实施，由中华人民共和国文化部指导，旨在加强家长对未成年人参与网络游戏的监护，引导未成年人健康、绿色参与网络游戏，和谐家庭关系的社会性公益行动。它提供了一种切实可行的方法，一种家长实施监控的管道，使家长纠正部分未成年子女沉迷游戏的行为成为可能。"
          }]
        }, {
          "title": "申请引导",
          "description": [{
            "content": "一、申请条件"
          }, {
            "content": "1、申请人需为被监护未成年人的法定监护人；"
          }, {
            "content": "2、申请人的被监护人年龄小于18周岁；"
          }, {
            "content": "3、申请人需为大陆公民，不含港、澳、台人士。 "
          }, {
            "content": "二、申请需要提交材料："
          }, {
            "content": "1、监护人信息表（包含监护人的身份证明复印件）；参见附表一 ",
            "attachment": {
              "content": "附件一",
              "url": "http://hegsxd.com/1.doc"
            }

          }, {
            "content": "2、被监护人信息表（包含被监护人所玩游戏相关信息及身份证明复印件）；参见附表二 ",
            "attachment": {
              "content": "附件二",
              "url": "http://hegsxd.com/2.doc"
            }
          }, {
            "content": "3、填写未成年人家长监护申请书、起诉保证书、授权书并手工签字（需下载，填写并打印，签字）；参见附表三 ",
            "attachment": {
              "content": "附件三",
              "url": "http://hegsxd.com/3.doc"
            }
          }, {
            "content": "4、申请人与被监护人的监护关系证明文件（户口簿或有关机关出具的证明文件）。"
          }, {
            "content": "账户疑义申请文档  ",
            "attachment": {
              "content": "附件四",
              "url": "http://hegsxd.com/4.doc"
            }
          }, {
            "content": "三、申请方式"
          }, {
            "content": "邮寄地址：新疆伊犁州霍尔果斯市北京路以西、珠海路以南合作中心配套区查验业务楼8楼8-13-85号    客服中心 收"
          }, {
            "content": "邮政编码：835221"
          }, {
            "content": "四、申请流程： "
          }, {
            "content": "申请人首先使用信件、来访等方式提交资料；受理公司在收到提交材料后，将在48小时内进行电话回访（不含法定节假日），由受理公司对内容进行核查。资料提交合格且核对正确的情况下，由受理公司对该请求予以受理；资料提交不全面的，由受理公司进行回访，并提示申请人继续补充材料；资料提交不合格且不正确的，受理公司有权对该请求予以拒绝，并附说明理由。"
          }, {
            "content": "五、其他要求："
          }, {
            "content": "1、申请人应提交较完备的申请材料，对未提供的信息要及时补充；可请熟知电脑、互联网、游戏的人员进行协助，以便提供详实资料；"
          }, {
            "content": "2、申请人应保证提交的信息真实有效；对于提供虚假信息或伪造证件，监护关系证明书追究法律责任的权利。"
          }]
        }, {
          "title": "家长监护服务说明",
          "description": [{
            "content": "家长监护工程充分考虑家长的实际需求，当家长发现自己的孩子玩游戏过于沉迷的时候，由家长提供合法的监护人资质证明、游戏名称账号、以及家长对于限制强度的愿望等信息，可对处于孩子游戏沉迷状态的账号采取几种限制措施，解决未成年人沉迷网游的不良现象，如限制孩子每天玩游戏的时间区间和长度，也可以限制只有周末才可以游戏，或者完全禁止。"
          }]
        }]
      }
    }
  }
}

=== lizzyl/bootstrap-test/data/pay.json
{
  "head": {
    "meta": {
      "keywords": "霍尔果斯炫动网络官网",
      "description": "霍尔果斯炫动网络官网",
      "author": "your-name@hoolai.com"
    },
    "title": "关于公司"
  },
  "header": {
    "logo": {
      "src": "http://cdn.hoolaiimg.com/group1/M00/00/2B/CgIJKlg-iz2ARC8SAAAjKGI-JWw474.png",
      "url": "./"
    },
    "nav": [{
      "name": "首页",
      "url": "./index.html"
    }, {
      "name": "关于我们",
      "url": "./about.html"
    }, {
      "name": "家长监护工程",
      "url": "./custody.html"
    }, {
      "name": "在线交易",
      "url": "./pay.html"
    }, {
      "name": "服务协议",
      "url": "./server.html"
    }, {
      "name": "隐私协议",
      "url": "./privacy.html"
    }, {
      "name": "纠纷处理",
      "url": "./dispute.html"
    }],
    "account": {
      "signup": {
        "name": "注册",
        "url": "/signup.html"
      },
      "signin": {
        "name": "登陆",
        "url": "/signin.html"
      },
      "logout": {
        "name": "注销",
        "url": "/logout.html"
      }
    }
  },
  "footer": {
    "copyright": "霍尔果斯炫动网络科技有限公司",
    "address": "新疆伊犁州霍尔果斯市北京路以西、珠海路以南合作中心配套区查验业务楼8楼8-13-85号"
  },
  "content": {
    "carousel": [{
      "src": "http://www.hoolai.com/assets/images/about_hoolai.jpg"
    }],
    "main": {}
  }
}

=== lizzyl/bootstrap-test/data/privacy.json
{
  "head": {
    "meta": {
      "keywords": "霍尔果斯炫动网络官网",
      "description": "霍尔果斯炫动网络官网",
      "author": "your-name@hoolai.com"
    },
    "title": "官网首页"
  },
  "header": {
    "logo": {
      "src": "http://cdn.hoolaiimg.com/group1/M00/00/2B/CgIJKlg-iz2ARC8SAAAjKGI-JWw474.png",
      "url": "./"
    },
    "nav": [{
      "name": "首页",
      "url": "./index.html"
    }, {
      "name": "关于我们",
      "url": "./about.html"
    }, {
      "name": "家长监护工程",
      "url": "./custody.html"
    }, {
      "name": "在线交易",
      "url": "./pay.html"
    }, {
      "name": "服务协议",
      "url": "./server.html"
    }, {
      "name": "隐私协议",
      "url": "./privacy.html"
    }, {
      "name": "纠纷处理",
      "url": "./dispute.html"
    }],
    "account": {
      "signup": {
        "name": "注册",
        "url": "./signup.html"
      },
      "signin": {
        "name": "登陆",
        "url": "./signin.html"
      },
      "logout": {
        "name": "注销",
        "url": "./logout.html"
      }
    }
  },
  "footer": {
    "copyright": "霍尔果斯炫动网络科技有限公司",
    "address": "新疆伊犁州霍尔果斯市北京路以西、珠海路以南合作中心配套区查验业务楼8楼8-13-85号"
  },
  "content": {
    "carousel": [{
      "src": "http://cdn.hoolaiimg.com/group1/M00/00/29/CgIJKlfogeWAbJZmAALTKsqjajs799.jpg?v=0.0.1"
    }, {
      "src": "http://cdn.hoolaiimg.com/group1/M00/00/28/PBzLUVc6fvSAeUi8AAMYBqU2do0253.jpg?v=0.0.1"
    }],
    "main": {
      "privacy": {
        "title": "隐私权保护声明",
        "description": [{
          "content": "互爱互动（北京）科技有限公司（\"互爱\"、\"我们\"、\"我方\" 或 \"我们的\"）的名义表示，尊重本游戏平台访问者的隐私。 您与我们之间的隐私政策旨在告知您我们关于收集、使用和披露您通过游戏平台提交给我们的任何个人信息和匿名信息的政策和行为规范。"
        }, {
          "content": "互爱注重保护用户个人信息及个人隐私。本隐私权保护声明解释了用户个人信息收集和使用的有关情况，本隐私权保护声明适用于互爱的所有相关服务。"
        }],
        "content": [{
          "title": "您个人信息的收集",
          "description": [{
            "content": "互爱为用户提供游戏及相关服务。在您注册、使用互爱提供的游戏或相关服务时，经您的同意，我们收集与个人身份有关的信息，例如姓名、住址、手机号码等。如果您无法提供此类信息，可能会不能使用对应服务。"
          }, {
            "content": "我们也会基于优化用户体验的目的，收集其他有关的信息。例如当用户访问互爱游戏平台，我们收集哪些游戏的受欢迎程度、浏览器软件信息等以便优化我们的游戏平台服务。"
          }]
        }, {
          "title": "您个人信息的管理",
          "description": [{
            "content": "互爱会在如下情形使用您的个人信息：(1)符合法律法规的要求；（2）根据您的授权；（3）符合互爱相关服务条款、软件许可使用协议的约定；"
          }, {
            "content": "互爱不会未经允许向第三方披露您的个人信息。除非满足下述情形之一： (1)根据法律法规的规定；（2）符合您与互爱之间的相关服务条款、软件许可使用协议的约定；"
          }]
        }, {
          "title": "您个人信息的安全",
          "description": [{
            "content": "互爱严格保护您的个人信息安全。我们使用各种制度、安全技术和程序等措施来保护您的个人信息不被未经授权的访问、使用或泄漏。如果您对我们的个人信息保护有任何疑问，请联系我们。"
          }]
        }, {
          "title": "访问您的个人信息",
          "description": [{
            "content": "如果您注册了互爱相关服务，您可以查阅或编辑您提交给互爱的个人信息。一般情况下，您可随时浏览、修改自己提交的信息，但出于安全性和身份识别（如号码申诉服务）的考虑，您可能无法修改注册时提供的初始注册信息及其他验证信息。"
          }]
        }, {
          "title": "Cookie 的使用",
          "description": [{
            "content": "互爱使用 Cookie 来帮助您实现您的联机体验的个性化。Cookie 是由网络服务器存放在您的访问设备上的文本文件。指定给您的 Cookie 是唯一的，它只能被将 Cookie 发布给您的域中的 Web 服务器读取。"
          }, {
            "content": "我们可能使用「Cookies档案」收集用户对服务的使用数据，这样有助于用户再度到访网站时之用。「Cookies档案」是由网络服务器发出的一小段数据，储存于网络浏览器之中，使日后可从该浏览器阅读该段数据。目前，从Cookies档案收集到的资料用于提高服务的功能。互爱服务所提供的数据，是根据互爱就用户对服务的累积使用进行分析，然后加以组织和编排的。Cookies档案有助同时能使登入程序更顺畅更快捷，以及保存通话期之间的数据。"
          }, {
            "content": "您可以关闭您浏览器上的Cookies档案功能而不影响到您浏览游戏所在的游戏平台网站，但Cookies档案确实可使我们服务更方便。关闭Cookies档案功能可能会造成使用的复杂程度和涉及较多的输入手续。您亦应留意，若您清除Cookies档案功能，，则可能影响到互爱服务的某些功能。"
          }]
        }, {
          "title": "未成年人的个人信息保护",
          "description": [{
            "content": "互爱非常重视对未成年人个人信息的保护。若您是18周岁以下的未成年人，在使用互爱提供的服务前，应事先取得您家长或法定监护人的书面同意。互爱根据国家相关法律法规的规定保护未成年人的个人信息。"
          }, {
            "content": "互爱会不时更新本隐私权保护声明。我们会在游戏平台上发布对隐私权声明所做的变更内容。"
          }, {
            "content": "(全文完)"
          }]
        }]
      }
    }
  }
}
